"""Internal helper: generates reseed_from_export.py with embedded SQL."""
import sqlite3
import sys
from pathlib import Path

SCRIPT_DIR  = Path(__file__).parent
SEED_SQL    = SCRIPT_DIR / "db" / "seed_current.sql"
OUTPUT      = SCRIPT_DIR / "reseed_from_export.py"
SCHEMA_FILE = SCRIPT_DIR / "db" / "schema.sql"

if not SEED_SQL.exists():
    print(f"ERROR: {SEED_SQL} not found — run export_seed.py first", file=sys.stderr)
    sys.exit(1)

sql_content = SEED_SQL.read_text(encoding="utf-8")

# Sanity-check: the SQL must not contain the closing delimiter we will use
DELIM = "SEED_END"
if DELIM in sql_content:
    print(f"ERROR: seed SQL contains reserved delimiter '{DELIM}'", file=sys.stderr)
    sys.exit(1)

generated_note = f"# Generated by _gen_reseed.py from {SEED_SQL.name}"

script = f'''\
"""
reseed_from_export.py — Self-contained ActionHub data reseeder
==============================================================
Contains the exported database snapshot directly as embedded SQL.
No external files required — just run this script.

Usage
-----
    python reseed_from_export.py               # load into default DB
    python reseed_from_export.py path/to.db    # explicit target
    python reseed_from_export.py --reinit      # drop schema + reload
"""
{generated_note}

import argparse
import sqlite3
import sys
from pathlib import Path

SCRIPT_DIR  = Path(__file__).parent
DEFAULT_DB  = SCRIPT_DIR / "db" / "actionhub.db"
SCHEMA_FILE = SCRIPT_DIR / "db" / "schema.sql"

# ---------------------------------------------------------------------------
# Embedded seed data
# ---------------------------------------------------------------------------
SEED_SQL = """\
{sql_content}"""


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Load embedded seed data into ActionHub database."
    )
    parser.add_argument(
        "database", nargs="?", default=str(DEFAULT_DB),
        help=f"Target SQLite database (default: {{DEFAULT_DB}})",
    )
    parser.add_argument(
        "--reinit", action="store_true",
        help="Wipe and recreate the DB from schema.sql before loading (destroys existing data).",
    )
    args = parser.parse_args()

    db_path = Path(args.database)

    if args.reinit:
        if not SCHEMA_FILE.exists():
            print(f"ERROR: schema file not found: {{SCHEMA_FILE}}", file=sys.stderr)
            return 1
        if db_path.exists():
            db_path.unlink()
            print(f"Removed existing database: {{db_path}}")
        db_path.parent.mkdir(parents=True, exist_ok=True)
        conn = sqlite3.connect(str(db_path))
        conn.execute("PRAGMA journal_mode = WAL")
        conn.execute("PRAGMA foreign_keys = OFF")
        try:
            conn.executescript(SCHEMA_FILE.read_text(encoding="utf-8"))
            conn.commit()
            print("Schema created.")
        except sqlite3.Error as exc:
            print(f"ERROR: schema creation failed — {{exc}}", file=sys.stderr)
            conn.close()
            return 1
    else:
        if not db_path.exists():
            print(f"ERROR: database not found: {{db_path}}", file=sys.stderr)
            print("Run  python init_db.py  first, or pass --reinit.", file=sys.stderr)
            return 1
        conn = sqlite3.connect(str(db_path))
        conn.execute("PRAGMA journal_mode = WAL")
        conn.execute("PRAGMA foreign_keys = OFF")

    print("Loading embedded seed data …")
    try:
        conn.executescript(SEED_SQL)
        conn.commit()
    except sqlite3.Error as exc:
        print(f"ERROR: seed load failed — {{exc}}", file=sys.stderr)
        conn.close()
        return 1

    conn.execute("PRAGMA foreign_keys = ON")
    conn.close()
    print(f"Done. Database ready at: {{db_path}}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''

OUTPUT.write_text(script, encoding="utf-8")
print(f"Written: {OUTPUT}")
