from __future__ import annotations

from datetime import datetime, timedelta

from actionhub import create_app
from actionhub.auth.service import create_user
from actionhub.middleware.db import get_db
from actionhub.utils.ref_generator import generate_action_ref
from actionhub.workflow import engine


DEMO_PREFIX = "WF Demo"


def _ensure_demo_users() -> dict[str, int]:
    """Create demo users if missing and return their IDs."""
    users = {
        "teamlead": {
            "username": "wf_teamlead",
            "employee_id": "100101",
            "password": "Demo@2026",
            "display_name": "WF Team Lead",
            "email": "wf_teamlead@actionhub.local",
            "role": "TeamLead",
        },
        "facility": {
            "username": "wf_facility",
            "employee_id": "100102",
            "password": "Demo@2026",
            "display_name": "WF Facility",
            "email": "wf_facility@actionhub.local",
            "role": "Member",
        },
        "hse": {
            "username": "wf_hse",
            "employee_id": "100103",
            "password": "Demo@2026",
            "display_name": "WF HSE",
            "email": "wf_hse@actionhub.local",
            "role": "Member",
        },
        "finance": {
            "username": "wf_finance",
            "employee_id": "100104",
            "password": "Demo@2026",
            "display_name": "WF Finance",
            "email": "wf_finance@actionhub.local",
            "role": "Member",
        },
        "ot": {
            "username": "wf_ot",
            "employee_id": "100105",
            "password": "Demo@2026",
            "display_name": "WF OT Admin",
            "email": "wf_ot@actionhub.local",
            "role": "Member",
        },
    }

    user_ids: dict[str, int] = {}
    for key, user in users.items():
        user_ids[key] = create_user(
            username=user["username"],
            employee_id=user["employee_id"],
            password=user["password"],
            display_name=user["display_name"],
            email=user["email"],
            role=user["role"],
            must_change_pwd=0,
        )
    return user_ids


def _get_template_id(db, wft_type: str, preferred_name: str | None = None) -> int:
    if preferred_name:
        row = db.execute(
            """SELECT wft_id FROM t_workflow_template
               WHERE wft_active = 1 AND wft_type = ? AND wft_name_en = ?
               ORDER BY wft_id LIMIT 1""",
            (wft_type, preferred_name),
        ).fetchone()
        if row:
            return int(row["wft_id"])

    row = db.execute(
        """SELECT wft_id FROM t_workflow_template
           WHERE wft_active = 1 AND wft_type = ?
           ORDER BY wft_is_default DESC, wft_id
           LIMIT 1""",
        (wft_type,),
    ).fetchone()
    if not row:
        raise RuntimeError(f"No active workflow template found for type={wft_type}")
    return int(row["wft_id"])


def _create_action(db, title: str, creator_id: int) -> int:
    existing = db.execute(
        "SELECT act_id FROM t_action WHERE act_title = ? LIMIT 1", (title,)
    ).fetchone()
    if existing:
        return int(existing["act_id"])

    now = datetime.now().isoformat()
    deadline = (datetime.now() + timedelta(days=14)).date().isoformat()
    cursor = db.execute(
        """INSERT INTO t_action
           (act_ref, act_title, act_desc, act_status, act_priority, act_deadline,
            act_source, act_created_by, act_created_at)
           VALUES (?, ?, ?, 'Open', 'Medium', ?, 'Manual', ?, ?)""",
        (
            generate_action_ref(),
            title,
            f"Autogenerated demo workflow action for {title}",
            deadline,
            creator_id,
            now,
        ),
    )
    action_id = int(cursor.lastrowid)
    db.execute(
        """INSERT INTO t_assignment (asg_action_id, asg_user_id, asg_role, asg_status)
           VALUES (?, ?, 'Lead', 'Accepted')""",
        (action_id, creator_id),
    )
    db.commit()
    return action_id


def _instantiate_if_missing(db, template_id: int, action_id: int, started_by: int) -> int:
    row = db.execute(
        "SELECT wfi_id FROM t_workflow_instance WHERE wfi_action_id = ? LIMIT 1", (action_id,)
    ).fetchone()
    if row:
        return int(row["wfi_id"])
    instance_id = engine.instantiate_workflow(template_id, action_id, started_by)
    db.commit()
    return int(instance_id)


def _set_active_assignee(db, instance_id: int, step_key: str, assignee_id: int) -> None:
    db.execute(
        """UPDATE t_workflow_step_instance
           SET wsi_assignee_id = ?
           WHERE wsi_instance_id = ? AND wsi_step_key = ? AND wsi_status = 'Active'""",
        (assignee_id, instance_id, step_key),
    )
    db.commit()


def seed_workflow_demo() -> None:
    app = create_app()
    with app.app_context():
        db = get_db()
        users = _ensure_demo_users()


        # Remove all workflow templates except the demo
        db.execute("DELETE FROM t_workflow_template WHERE wft_name_en != ?", ("OT User Creation",))
        db.commit()

        from actionhub.workflow.service import create_template
        import json
        try:
            request_template_id = _get_template_id(db, "request", preferred_name="OT User Creation")
        except RuntimeError:
            # Minimal workflow graph for demo
            minimal_graph = {
                "steps": {
                    "request": {"type": "Task", "order": 1, "label": "Request"},
                    "done": {"type": "End", "label": "Done"}
                },
                "transitions": [
                    {"from": "request", "to": "done"}
                ]
            }
            request_template_id = create_template(
                name_en="OT User Creation",
                name_cn="OT用户创建",
                wft_type="request",
                graph=minimal_graph,
                created_by=1,  # fallback to admin user
                desc="Demo workflow for OT User Creation",
                is_default=True
            )

        # Only 1) Active request instance at first step (Team Lead queue)
        action_1 = _create_action(db, f"{DEMO_PREFIX} - OT Request Intake", users["teamlead"])
        inst_1 = _instantiate_if_missing(db, request_template_id, action_1, users["teamlead"])
        _set_active_assignee(db, inst_1, "request", users["teamlead"])

        counts = {
            "users": db.execute("SELECT COUNT(*) c FROM t_user").fetchone()["c"],
            "workflow_instances": db.execute("SELECT COUNT(*) c FROM t_workflow_instance").fetchone()["c"],
            "active_instances": db.execute(
                "SELECT COUNT(*) c FROM t_workflow_instance WHERE wfi_status = 'Active'"
            ).fetchone()["c"],
            "completed_instances": db.execute(
                "SELECT COUNT(*) c FROM t_workflow_instance WHERE wfi_status = 'Completed'"
            ).fetchone()["c"],
        }

        print("Workflow demo data seeded.")
        print(f"Users: {counts['users']}")
        print(f"Workflow instances: {counts['workflow_instances']}")
        print(f"Active instances: {counts['active_instances']}")
        print(f"Completed instances: {counts['completed_instances']}")
        print("Demo login accounts (password: Demo@2026):")
        print("  wf_teamlead / 100101")
        print("  wf_facility / 100102")
        print("  wf_hse / 100103")
        print("  wf_finance / 100104")
        print("  wf_ot / 100105")


if __name__ == "__main__":
    seed_workflow_demo()
